name: vendors
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.1
  firebase_auth: ^4.12.0
  firebase_storage: ^11.4.0
  fluttertoast: ^8.2.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  permission_handler: ^11.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  validators: ^3.0.0  
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  country_picker: ^2.0.22
  firebase_core: ^2.20.0
  mobile_scanner: ^3.5.2
  dotted_border: ^2.1.0
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  blue_thermal_printer: ^1.2.3
  bluetooth_print: ^4.3.0
  esc_pos_utils_plus: ^2.0.3
  flutter_esc_pos_utils: ^1.0.0
  flutter_pos_printer_platform_image_3: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"

flutter:
  uses-material-design: true

  
  assets:
    - assets/